### PR TITLE
add ocaml-for-programming link

### PR DESCRIPTION
**Pull request by dannywillems**
I created a repository with the same purpose than this manifesto and awesome-ocaml: discuss, listing, develop and reference tools about web programming.

It needs to be improve, hope it could be useful and wll have collaborations. 

I also added some points I think important:
- tutorials from scratch with useful applications: other languages/technologies have success because they provide tutorials with basics examples and exercices give you real applications.
- useful libraries not yet developed: as a student, I was looking for libraries which could have success and could be useful. I would have liked a repository like this to have inspirations. It could be also useful if an hackathon about ocaml is organized (such as for mirageOS).
- tutorials in different languages: other languages/technologies have also success because there are tutorials in a lot of languages. Some doesn't like or can't speak english (or french) and it's hard for them to learn OCaml if there are only tutorials in english or french.

### CODE REVIEW

**Comment by fxfactorial** [comment]
Thanks! I'm a little hesitant to merge because https://github.com/rizo/awesome-ocaml already does this for point 7 of mine, albeit not specialized to web, and I would prefer not diluting information. (I like the centrality of awesome-ocaml)

Can you remove the separate link for ocaml-for-web and change point 8 to be `to learn in their own language`, trivial fix but does remove the gendered language.

**Comment by dannywillems** [comment]
About Awesome ocaml, I had this answer several times particulary on IRC. Here my response:

```
I would like to have a single repo for web programming because it's a huge subject and
I think it can be more useful to discuss about web programming in OCaml seperately than
awesome-ocaml which contains other subjects. I think these repo are complementary. I
do PR on awesome-ocaml but I still think it's useful to list more deeply in a separate
repository.
```

Ok to change point 8.

What about point 7 ?

**Comment by fxfactorial** [comment]
@dannywillems yea, about point 7, would prefer to not split off awesome-ocaml's mindshare. Maybe when the web programming part becomes too unwieldy or large, then split it off.

**Comment by dannywillems** [comment]
@fxfactorial What's the similitude between awesome-ocaml and point 7 ? Point 7 says to create a repo for project which are not developed but could be useful.

Or do you think it must be on awesome-ocaml in a seperate section ?

**Comment by fxfactorial** [comment]
@dannywillems oh sorry, miscommunication. Point 7 about the repo for listing useful libraries not yet developed/starter projects is a great idea. People often ask for ideas about how to get started, I tend to suggest they do a pretty printing of bitcoin prices using yojson + cohttp.

I talking about this point 7

```
 programming. See [ocaml for web
 programming](https://github.com/dannywillems/ocaml-for-web-programming) for
 discussions, todo and tools about web programming in ocaml.
```

This I think is better kept under awesome-ocaml's own web programming section.

**Comment by dannywillems** [comment]
No problem. I will do it tonight.

**Comment by fxfactorial** [comment]
@dannywillems Thanks so much!

**Comment by dannywillems** [comment]
@fxfactorial Done. (Don't want to rebase, just a new commit. Sorry if it's ugly).
EDIT: I forgot to change the point 8, sorry.

**Pull request merged**
